# -*- coding: utf-8 -*-
"""notebookb4fd592ca3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/khushisharma1210/notebookb4fd592ca3.c59647cf-678b-4f53-baf7-7f5bad26b8a8.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260204/auto/storage/goog4_request%26X-Goog-Date%3D20260204T205902Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D58d907999fd50b09878c1fd1d55a847db927678dc0d9239f12502e63d5fdda45341e54909a488b65b8a2d8b0ef9fe9bf3f1eebb0a0aeb61d07155c27908da04626c33a82e7728fde184ef0b3fe735db7b5e68bd4cd289c6e548150152ed3be04f5b84edacf4312eced37719c97c0f862f43ea85f955ed9e3ab9779611c050b174dc80188559f6beb78dfa3cc4104f64ddeb53be0f1484781a66161ac1970ca4443cf6a910ea10113a58e8244db9900a2728f6f39d8a0891fc9bbe5e0c98387dacc6e2b3085a295de62f09406ee3c6857ce198156facc7383dc3d5c2601d3314ceb0e57d39aa5e66cbe800b1584643f3f654255fcd906e51cd8ba3436b419ef36
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

mlp_term_3_2025_kaggle_assignment_3_path = kagglehub.competition_download('mlp-term-3-2025-kaggle-assignment-3')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

#  Imports and Data Loading
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from scipy.sparse import hstack
import scipy.sparse

# Load datasets (Ensure files are in the same directory)
train_df = pd.read_csv('/kaggle/input/mlp-term-3-2025-kaggle-assignment-3/train.csv')
test_df = pd.read_csv('/kaggle/input/mlp-term-3-2025-kaggle-assignment-3/test.csv')
sample_sub = pd.read_csv('/kaggle/input/mlp-term-3-2025-kaggle-assignment-3/sample_submission.csv')

print(f"Train shape: {train_df.shape}")
print(f"Test shape: {test_df.shape}")

"""**Rubric 1: Data Types & Descriptive Statistics**"""

# RUBRIC: Identify data types of different columns
print("--- Data Types ---")
print(train_df.info())

# RUBRIC: Present descriptive statistics of numerical columns
print("\n--- Descriptive Statistics ---")
print(train_df.describe())

"""**Rubric 2: Data Cleaning (Missing, Duplicates, Outliers)**"""

# Handling Missing Values, Duplicates, and Outliers

# RUBRIC: Identify and handle missing values
print("\n--- Missing Values Before Imputation ---")
print(train_df.isnull().sum())


train_df['phrase'] = train_df['phrase'].fillna('')
test_df['phrase'] = test_df['phrase'].fillna('')

# RUBRIC: Identify and handle duplicates
duplicates = train_df.duplicated().sum()
print(f"\nNumber of duplicate rows found: {duplicates}")
if duplicates > 0:
    train_df.drop_duplicates(inplace=True)
    print("Duplicates dropped.")
else:
    print("No duplicates to drop.")

# RUBRIC: Identify and handle outliers

num_cols = ['feature_1', 'feature_2', 'feature_3']

plt.figure(figsize=(12, 4))
for i, col in enumerate(num_cols):
    plt.subplot(1, 3, i+1)
    sns.boxplot(y=train_df[col])
    plt.title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()

# Handling Outliers: Clipping to 1st and 99th percentiles to preserve data but remove extremes
print("\n--- Handling Outliers (Clipping) ---")
for col in num_cols:
    lower_bound = train_df[col].quantile(0.01)
    upper_bound = train_df[col].quantile(0.99)
    train_df[col] = np.clip(train_df[col], lower_bound, upper_bound)
    print(f"Clipped {col} to range: [{lower_bound:.4f}, {upper_bound:.4f}]")

"""**Rubric 3: Visualizations**"""

# Visualizations and Insights

# RUBRIC: Present at least three visualizations and provide insights (10 points)

# Visualization 1: Target Variable Distribution
plt.figure(figsize=(6, 4))
sns.countplot(x='sentiment', data=train_df, palette='viridis')
plt.title("Distribution of Sentiment (Target)")
plt.show()

# Visualization 2: Text Length Analysis
train_df['text_len'] = train_df['phrase'].apply(len)
plt.figure(figsize=(8, 4))
sns.histplot(data=train_df, x='text_len', hue='sentiment', bins=30, kde=True)
plt.title("Text Length Distribution by Sentiment")
plt.show()

# Visualization 3: Correlation Heatmap of Numerical Features
plt.figure(figsize=(6, 5))
sns.heatmap(train_df[['feature_1', 'feature_2', 'feature_3', 'text_len']].corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

"""**Rubric 4: Preprocessing (Scaling & Encoding)**"""

# Feature Engineering, Scaling, and Encoding

# 1. Define X and y
X = train_df.drop(['id', 'sentiment', 'text_len'], axis=1)
y = train_df['sentiment']
X_test_final = test_df.drop(['id'], axis=1)

# Split for validation
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# RUBRIC: Scale Numerical features and Encode Categorical features (10 points)

# Text Encoding
tfidf = TfidfVectorizer(stop_words='english', max_features=10000, ngram_range=(1, 2), sublinear_tf=True)
X_train_text = tfidf.fit_transform(X_train['phrase'])
X_val_text = tfidf.transform(X_val['phrase'])
X_test_text = tfidf.transform(X_test_final['phrase'])

# Numerical Scaling
imputer = SimpleImputer(strategy='median')
scaler = StandardScaler()

X_train_num = imputer.fit_transform(X_train[num_cols])
X_train_num = scaler.fit_transform(X_train_num)

X_val_num = imputer.transform(X_val[num_cols])
X_val_num = scaler.transform(X_val_num)

X_test_num = imputer.transform(X_test_final[num_cols])
X_test_num = scaler.transform(X_test_num)

# Combine Features
X_train_combined = hstack([X_train_text, scipy.sparse.csr_matrix(X_train_num)])
X_val_combined = hstack([X_val_text, scipy.sparse.csr_matrix(X_val_num)])
X_test_combined = hstack([X_test_text, scipy.sparse.csr_matrix(X_test_num)])

print("Data Scaling and Encoding Complete.")

"""**Rubric 5: Model Building (7 Models)**"""

#  Model Building

# 1. Import all necessary models explicitly inside this cell to avoid NameErrors
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score

# RUBRIC: Model Building (at least 7 models)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(random_state=42, max_depth=10),
    "Random Forest": RandomForestClassifier(n_estimators=50, max_depth=10, random_state=42),
    "SGD Classifier": SGDClassifier(loss='hinge', random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=50, random_state=42),
    "AdaBoost": AdaBoostClassifier(n_estimators=50, random_state=42) # Replaced Ridge
}

results = []

print("Training 7 Models...")
for name, model in models.items():
    print(f"Training {name}...")
    model.fit(X_train_combined, y_train)
    val_pred = model.predict(X_val_combined)
    acc = accuracy_score(y_val, val_pred)
    results.append({"Model": name, "Validation Accuracy": acc})
    print(f"  -> Accuracy: {acc:.4f}")

"""**Rubric 6: Hyperparameter Tuning**"""

#  Hyperparameter Tuning

# 1. IMPORTS (Crucial to fix NameError)
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

# RUBRIC: Hyperparameter Tuning on any 3 of the models
print("\n--- Hyperparameter Tuning on 3 Models ---")

# Model 1: Tuning Logistic Regression
print("1. Tuning Logistic Regression...")
param_grid_lr = {'C': [0.1, 1, 10]}
# Use n_jobs=-1 to speed up tuning
grid_lr = GridSearchCV(LogisticRegression(max_iter=1000, random_state=42), param_grid_lr, cv=3, n_jobs=-1)
grid_lr.fit(X_train_combined, y_train)
print(f"Best LogReg Params: {grid_lr.best_params_}, Score: {grid_lr.best_score_:.4f}")

# Model 2: Tuning Decision Tree (Replaced LinearSVC to match Cell 6 models)
print("2. Tuning Decision Tree...")
param_grid_dt = {'max_depth': [10, 20, None], 'min_samples_split': [2, 5]}
grid_dt = GridSearchCV(DecisionTreeClassifier(random_state=42), param_grid_dt, cv=3, n_jobs=-1)
grid_dt.fit(X_train_combined, y_train)
print(f"Best Decision Tree Params: {grid_dt.best_params_}, Score: {grid_dt.best_score_:.4f}")

# Model 3: Tuning Random Forest
print("3. Tuning Random Forest...")
param_grid_rf = {'n_estimators': [50, 100], 'max_depth': [10, 20]}
grid_rf = GridSearchCV(RandomForestClassifier(random_state=42), param_grid_rf, cv=3, n_jobs=-1)
grid_rf.fit(X_train_combined, y_train)
print(f"Best RF Params: {grid_rf.best_params_}, Score: {grid_rf.best_score_:.4f}")

"""**Rubric 7: Model Comparison**"""

# Comparison of Model Performances

# RUBRIC: Comparison of model performances
results_df = pd.DataFrame(results).sort_values(by="Validation Accuracy", ascending=False)

print("\n--- Model Comparison Table ---")
print(results_df)

plt.figure(figsize=(10, 5))
sns.barplot(x="Validation Accuracy", y="Model", data=results_df, palette="viridis")
plt.title("Model Performance Comparison (Validation Accuracy)")
plt.xlim(0.5, 0.7) # Adjust based on scores to make differences visible
plt.show()

# Conclusion on best model
best_model_name = results_df.iloc[0]['Model']
print(f"The best performing model on validation data is: {best_model_name}")

#  Final Submission
from sklearn.svm import LinearSVC
from scipy.sparse import vstack # CRITICAL: Needed to stack rows


best_model = LinearSVC(C=0.4, dual=False, random_state=42)

X_full_train = vstack([X_train_combined, X_val_combined])
y_full_train = pd.concat([y_train, y_val])

# Retrain on the full dataset
print("Retraining best model on full data...")
best_model.fit(X_full_train, y_full_train)

# Predict on Test Set
final_preds = best_model.predict(X_test_combined)

# Create Submission File
submission_df = pd.DataFrame({
    'id': test_df['id'],
    'sentiment': final_preds
})

submission_df.to_csv('submission.csv', index=False)
print("Final submission.csv created successfully!")
print(submission_df.head())